version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      # named volumes
      - ./mongodb:/data/db

  server_py:
    build: .
    tty: true
    privileged: true
    restart: always
    depends_on: 
      - mongo
